# Generated by Django 2.2.6 on 2019-10-22 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_p_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='like_users_c',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
